# Generated by Django 2.0.6 on 2018-06-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_verification_uiid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_uiid',
            new_name='verification_uuid',
        ),
    ]
